"""initial comit

Revision ID: 4659033058cd
Revises: 
Create Date: 2025-01-30 01:28:37.678655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4659033058cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('startDate', sa.String(length=10), nullable=False),
    sa.Column('endDate', sa.String(length=10), nullable=False),
    sa.Column('failedMembers', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('lastMessage', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('progressInterval', sa.String(length=20), nullable=False),
    sa.Column('progressIntervalDeadline', sa.String(length=10), nullable=False),
    sa.Column('progressIntervalsCompleted', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=201), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('solana_public_key', sa.String(length=100), nullable=False),
    sa.Column('solana_private_key', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solana_public_key'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contract_members',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('contract_id', 'user_id')
    )
    op.create_table('invited_users',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('contract_id', 'user_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('intervalDeadline', sa.String(length=10), nullable=False),
    sa.Column('intervalsTot', sa.Integer(), nullable=False),
    sa.Column('intervalsCompleted', sa.Text(), nullable=False),
    sa.Column('repsTot', sa.Integer(), nullable=False),
    sa.Column('repsCompleted', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(length=2083), nullable=True),
    sa.Column('read_by', sa.JSON(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('tasks')
    op.drop_table('invited_users')
    op.drop_table('contract_members')
    op.drop_table('user')
    op.drop_table('contracts')
    # ### end Alembic commands ###
