"""nullable content

Revision ID: 843f153b59ec
Revises: 5879f476d58a
Create Date: 2025-01-25 12:47:49.298169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843f153b59ec'
down_revision = '5879f476d58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
