"""much

Revision ID: 99be8cd07a70
Revises: 35e59d2ade96
Create Date: 2025-01-18 16:02:21.408585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99be8cd07a70'
down_revision = '35e59d2ade96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_members',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('contract_id', 'user_id')
    )
    op.drop_table('group_members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_members',
    sa.Column('contract_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('contract_id', 'user_id')
    )
    op.drop_table('contract_members')
    # ### end Alembic commands ###
